### ISSUE TITLE
Application-based signatures

### ISSUE THREAD

**Issue by waynerobinson** [chriswarren/doorkeeper-jwt#2]
I'd prefer not to have a single secret or key-pair shared across all the applications using JWT tokens.

I've looked at a few other implementations of JWT, including external services like Auth0. A lot of these have some type of application/partner reference they set in the `aud` claim and then lookup a secret based on this.

Is this something you're either looking at doing or would accept as a pull request? The application UID set in the `aud` and the application secret used to sign the message when using HS\* encryption and the application secret used as the public key when using RS\* encryption?

**Comment by chriswarren** [comment]
I'd definitely be interested in seeing this added as a PR if you're interested in giving it a go. Thanks!

**Comment by uxtronaut** [comment]
I have only tested the above PR with the authorization grant, specifically on the `Doorkeeper::TokensController#create` route when requesting `grant_type: 'authorization_code'`.

```ruby
class Doorkeeper::TokensControllerTest < ActionController::TestCase

  it 'responds with a valid JWT token' do
    a = create(:account)
    app = create(:app)

    sign_in(a)

    token = create(:access_grant, {
      application: app
    })

    @controller.stubs(:doorkeeper_token).returns(token)

    post :create, {
      client_id: app.uid,
      client_secret: app.secret,
      redirect_uri: token.redirect_uri,
      grant_type: 'authorization_code',
      code: token.token
    }

    assert_response :ok
    assert JWT.decode(JSON.parse(response.body)['access_token'], app.secret)
  end

end
```
