### ISSUE TITLE
Update jwt dependency to 2.1.0

### ISSUE THREAD

**Issue by knightq** [chriswarren/doorkeeper-jwt#21]
There have been a lot of [changes / bugfixes](https://github.com/jwt/ruby-jwt/blob/master/CHANGELOG.md#210-2017-10-06) since jwt 1.5.6.

It would be better to update this dependency.

**Comment by chriswarren** [comment]
Thanks. Would you be willing to take a look at updating it and seeing what needs to be done to get it working? I'm not currently using this gem in production and won't have a chance to dig in to it myself soon.
