### ISSUE TITLE
Using example config fails with 'Doorkeeper::JWT does not respond to .generate'

### ISSUE THREAD

**Issue by jondoe1337** [chriswarren/doorkeeper-jwt#22]
When using the example config from Readme - token POST request fails with
```
{
    "error": "Doorkeeper::JWT does not respond to `.generate`.",
    "error_description": "The authorization server encountered an unexpected condition which prevented it from fulfilling the request."
}
```
I still have no clue why this should fail though.

**Comment by chriswarren** [comment]
Sorry for the delay in getting back to you on this - have you managed to figure anything out?

My first guess is that you might be using a newer version of Doorkeeper than Doorkeeper-JWT currently supports.

**Comment by jondoe1337** [comment]
Nope. 

I used the newest gem available (but I can't remeber which one). Your doc says, 2.2.0 or newer, so I guess there are no upper boundaries?

**Comment by chriswarren** [comment]
Unfortunately I am not actively using Doorkeeper or this gem these days, so I haven't kept it up to date.

Looks like Doorkeeper is up to version 4.2.6 now. I wouldn't be surprised to find that they've introduced incompatible changes during that time.

If you're interested in taking a look at what's failing and trying to fix it, I'd be happy to try to help as I can, and thrilled to get a PR updating it. I am not going to be able to try to do so myself any time soon.

I'll update the readme to specify that this will likely only work w/ version 2.x of Doorkeeper in the meantime.

**Comment by jondoe1337** [comment]
Dito. We have found another way and used Knock for our purposes. I also cannot really assist in this issue right now. :-(

But thanks for the readme update.

**Comment by MarkMurphy** [comment]
This was an issue with Doorkeeper. See https://github.com/doorkeeper-gem/doorkeeper/issues/943

**Comment by chriswarren** [comment]
Oh awesome. Thanks for letting us know @MarkMurphy!
