### ISSUE TITLE
upgrade version of jwt requirement

### ISSUE THREAD

**Issue by gencer** [chriswarren/doorkeeper-jwt#23]
Currently targeted version of jwt gem is too old. This causes incompatibility with my other gems. I'm sure many others will do soon. or already.

Can we upgrade so we can use it with v2.1.x branch of JWT? Currently I tested against 2.1.0 and it just works.

**Comment by chriswarren** [comment]
If you'd like to make a PR for this I'd gladly pull it in. I'm not actively using this gem currently, and don't have a lot of time to update it right now.
