### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by mbajur** [chriswarren/doorkeeper-jwt#9]
Hello!

I'm trying to use that gem in my application but i can't do that. I actually don't even know if i'm doing it right. Anyway, i have a jwt token generated by ruby-jwt, using secret key of my rails app.

Sending a requests to my oauth2 api with a header `Authorization: Bearer <my token>` results in 401. What's weird - i can see in the server console that doorkeeper tries to find that token i'm sending in the doorkeeper tables and, if i understand JWT properly, that should not happen at all?

![image](https://cloud.githubusercontent.com/assets/581569/15107232/e014f012-15ce-11e6-9b56-364b32cfb178.png)

I would be really thankfull for any usage example or ideas on what might be wrong in my approach. Thanks in advance!
- doorkeeper 3.1.0
- doorkeeper-jwt 0.1.4

**Comment by zxr90** [comment]
hello, 

You dont need the ruby-jwt gem. You just need to specfiy the custom token generator to be used by doorkeeper.
See this https://github.com/doorkeeper-gem/doorkeeper#custom-access-token-generator
